### ISSUE TITLE
Running the docker

### ISSUE THREAD

**Issue by AliD201** [fethica/jikan-rest-docker#5]
Greetings, 
i am pretty new to these topics so sorry for any weird questions in advance.

i was trying to host the docker on my machine using **Visual studio code** though after building the image i can't run it using it's own default run which is run-jikan.sh ( since i am on windows i guess?)
and my only way to run it was to type the command on powershell
` docker-compose up -d`
 which is ok but what if i wanted to host it some where like azure, it uses the default run in the image.
i tried to change the docker file to be like this 
`ENTRYPOINT ["docker-compose up -d"]`
but it doesn't seem to work. 
here is the output when i just click run on the image 

`docker run --rm -d  -p 80:80/tcp jikan-rest-img:latest`

`27004a1db29323974690dbe91518d85e6c02b927d5005868b98b475662b7ecbd
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./run-jikan.sh\": stat ./run-jikan.sh: no such file or directory": unknown.`

even the ports it is not using the 9000:80 by default, i tried it but it is the same

Thank you.

**Comment by zunjae** [comment]
The instructions are right here https://github.com/fethica/jikan-rest-docker#installation what do you not understand?
